### ISSUE TITLE
数据集什么时候开源？

### ISSUE THREAD

**Issue by YangPanHZAU** [long123524/BsiNet-torch#1]
您使用了很多GF2和GF1号数据，是否可以考虑将地理坐标脱敏后开源矢量地块标注和高分影像

**Comment by long123524** [comment]
感谢您的关注。由于数据的敏感性等问题及其科研需要，我们暂未考虑将其他数据进行开源。但是，我们上传了一景山东的GF2，供用户使用，用户可以在已上传的影像中进行地块标注。我们也会继续推进该工作，争取早日贡献更好更大的数据集供用户使用。
