### ISSUE TITLE
Comparison of models in the research paper

### ISSUE THREAD

**Issue by kcsumesh** [long123524/BsiNet-torch#12]
This question is related to the comparison of models in the research paper - [Delineation of agricultural fields using multi-task BsiNet from high-resolution satellite images](https://www.sciencedirect.com/science/article/pii/S1569843222000735). You have compared the performance of BsiNet with three other models (UNet, Psi-Net, and ResUNet-a D7). The original implementation of ResUNet-a D7 is in [mxnet](https://mxnet.incubator.apache.org/) DL framework. Did you translate it into PyTorch or relied on the original implementation in mxnet?

**Comment by long123524** [comment]
> This question is related to the comparison of models in the research paper - [Delineation of agricultural fields using multi-task BsiNet from high-resolution satellite images](https://www.sciencedirect.com/science/article/pii/S1569843222000735). You have compared the performance of BsiNet with three other models (UNet, Psi-Net, and ResUNet-a D7). The original implementation of ResUNet-a D7 is in [mxnet](https://mxnet.incubator.apache.org/) DL framework. Did you translate it into PyTorch or relied on the original implementation in mxnet?
We mainly referring to the implementaion of tensforflow version (https://github.com/ChienWong/ResUnet-a) based on the MXNet verison.

**Comment by kcsumesh** [comment]
It seems like [ChienWong](https://github.com/ChienWong/ResUnet-a)'s implementation is a single-task model. How did you do it?

**Comment by long123524** [comment]
> It seems like [ChienWong](https://github.com/ChienWong/ResUnet-a)'s implementation is a single-task model. How did you do it?

You can combine the code of https://github.com/Akhilesh64/ResUnet-a. This also a important reference.

**Comment by kcsumesh** [comment]
Could you please share the code of ResUNet-a that you implemented for comparison with BsiNet?

**Comment by long123524** [comment]
> Could you please share the code of ResUNet-a that you implemented for comparison with BsiNet?

Sorry, I can't do that for the moment. You can to train resunte-a by referring to https://github.com/Akhilesh64/ResUnet-a or original MXNet framework, I have validated it, and it can be well-trainable and tested. Good luck!

**Comment by long123524** [comment]
> Could you please share the code of ResUNet-a that you implemented for comparison with BsiNet?

Sorry, I can't do that for the moment. You can to train resunte-a by referring to https://github.com/Akhilesh64/ResUnet-a (or original MXNet framework), I have validated it, and it can be well-trainable and tested. Good luck!
