### ISSUE TITLE
A test question

### ISSUE THREAD

**Issue by gxpde** [long123524/BsiNet-torch#13]
![屏幕截图 2024-10-20 183452](https://github.com/user-attachments/assets/2a813475-c0fd-48c4-b847-38c395511d9a)
请教一下产生这个的可能原因是？

**Comment by long123524** [comment]
> ![屏幕截图 2024-10-20 183452](https://private-user-images.githubusercontent.com/184810904/378178185-2a813475-c0fd-48c4-b847-38c395511d9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjI5MjEsIm5iZiI6MTcyOTQyMjYyMSwicGF0aCI6Ii8xODQ4MTA5MDQvMzc4MTc4MTg1LTJhODEzNDc1LWMwZmQtNDhjNC1iODQ3LTM4YzM5NTUxMWQ5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMTEwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjg2MTViNThiMTFjMzY5N2E4ZjllMjUzMjliMmRiY2JmMzg0Zjg2MTI2NTNmNjdhNDE5Yzk3MWU3NTc2NzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.inBp4xeQsm4SM9RBiyEsDESov43Va_SPDhtvEoUJeJc) 请教一下产生这个的可能原因是？

检查mask的读取路径是否正确，目前没有读取到mask信息。

**Comment by gxpde** [comment]
![屏幕截图 2024-10-20 183452](https://github.com/user-attachments/assets/f9ea60d1-1a5e-44fa-9adb-3769bed990cb)
![屏幕截图 2024-10-20 193242](https://github.com/user-attachments/assets/59dcba19-e5af-4782-98c6-08c170a184fa)
![屏幕截图 2024-10-20 193303](https://github.com/user-attachments/assets/3e3a979b-d107-427a-b38d-fa80edf810df)
我将文件路径输出之后，可以看到是与文件夹中的位置一致的

**Comment by gxpde** [comment]
![屏幕截图 2024-10-20 193303](https://github.com/user-attachments/assets/2830eed9-c5c0-431a-95cb-741986d268ad)
![屏幕截图 2024-10-20 193250](https://github.com/user-attachments/assets/0e7250f2-024f-4de3-a7c6-fb530bfa1c83)
![屏幕截图 2024-10-20 193242](https://github.com/user-attachments/assets/1fb21802-09cf-4d19-b5ed-03f724c67de7)
我将文件路径输出之后，可以看到是与文件夹中的位置一致的，所以问题应该不是这个吧

**Comment by long123524** [comment]
> ![屏幕截图 2024-10-20 193303](https://private-user-images.githubusercontent.com/184810904/378182430-2830eed9-c5c0-431a-95cb-741986d268ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjYwNTksIm5iZiI6MTcyOTQyNTc1OSwicGF0aCI6Ii8xODQ4MTA5MDQvMzc4MTgyNDMwLTI4MzBlZWQ5LWM1YzAtNDMxYS05NWNiLTc0MTk4NmQyNjhhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMjAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjEwYzcyZDc5N2I5MjZiYWE0OTAxZmEwYTUwYjg4MmYxYjNlNmM3ODUzYzVhZTNmZDRiZTllNjljMjRlZTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2gaXk0YGCP7ZW8-RPMSwx0CsZLjcJssAYv9DCFyYPGw) ![屏幕截图 2024-10-20 193250](https://private-user-images.githubusercontent.com/184810904/378182603-0e7250f2-024f-4de3-a7c6-fb530bfa1c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjYwNTksIm5iZiI6MTcyOTQyNTc1OSwicGF0aCI6Ii8xODQ4MTA5MDQvMzc4MTgyNjAzLTBlNzI1MGYyLTAyNGYtNGRlMy1hN2M2LWZiNTMwYmZhMWM4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMjAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDg1YmIzNzJmMGU1M2Y1NTFmMTMyZTEyZGZhZDAyYWU4ODYwZDJkZmQxZjM1YjRlMWU0NWI4OTc3NjQzYjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QrNsy6lwI0V7Ob5jZjOUqwnXewRKpOctskpJLCdl0Vg) ![屏幕截图 2024-10-20 193242](https://private-user-images.githubusercontent.com/184810904/378182620-1fb21802-09cf-4d19-b5ed-03f724c67de7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjYwNTksIm5iZiI6MTcyOTQyNTc1OSwicGF0aCI6Ii8xODQ4MTA5MDQvMzc4MTgyNjIwLTFmYjIxODAyLTA5Y2YtNGQxOS1iNWVkLTAzZjcyNGM2N2RlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMjAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDVlMmU1NTA3ZDYzOWUwMmYzODcxY2UxM2UyNDMxZmQ3ZjJhNzcxNjk0Yzg3ZDNjNDM4Mjg3ZmNmZDc3ZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ha8Vc6XRfEdOwo6AFL91apQvCBGHQvCprrTbsiRV68E) 我将文件路径输出之后，可以看到是与文件夹中的位置一致的，所以问题应该不是这个吧

你可以详细看一下数据加载的函数，你使用加载mask标签，但目前你的文件好像并没有它。不需要它删掉mask的加载函数即可，谢谢关注。
