### ISSUE TITLE
Where is the pretrain model?

### ISSUE THREAD

**Issue by chz8bit** [long123524/BsiNet-torch#2]
I can't find the model `--model_file ./model/150.pt` in Evaluate stage. Can you commit it, please.

**Comment by long123524** [comment]
Thank your concern. Can you provide a email? We will send a weight file to you.  We are trying to build a big dataset to train our model, improving generalization ability of model. At that time, we will upload a new weight file.

**Comment by long123524** [comment]
Thank your concern. Can you provide a email? We will send a weight file to you.  We are trying to build a big dataset to train our model, improving generalization ability of model. At that time, we will upload a new weight file.

**Comment by chz8bit** [comment]
> Thank your concern. Can you provide an email? We will send a weight file to you. We are trying to build a big dataset to train our model, improving generalization ability of model. At that time, we will upload a new weight file.

Thanks for your reply. This is my email, chz_work@outlook.com .

**Comment by afaq-ahmad** [comment]
@long123524  Hi, thanks for sharing your work; it's quite remarkable. I am also working on this research problem, and your model might be useful for me for generating some synthetic annotations. Can you please share the weights with me as well at this email: afaq.ahmad100@gmail.com

Thank you.

**Comment by long123524** [comment]
> 
Thank your concern. I have sent it to your email.

**Comment by NewGlad** [comment]
@long123524 Hi! Could you send the model to me? alexeynktn@yandex.ru Thanks!

**Comment by long123524** [comment]
> @long123524 Hi! Could you send the model to me? [alexeynktn@yandex.ru](mailto:alexeynktn@yandex.ru) Thanks!
Thanks. I have sent it to your email.

**Comment by raider377** [comment]
@long123524  Hi! Could you send the model to me? 
rein54@mail.ru

**Comment by long123524** [comment]
> @long123524 Hi! Could you send the model to me? [rein54@mail.ru](mailto:rein54@mail.ru)

Thanks. I have done.

**Comment by huazai-1994** [comment]
Could you send the model to me? zjhxgg1994@gmail.com Thanks

**Comment by long123524** [comment]
> Could you send the model to me? [zjhxgg1994@gmail.com](mailto:zjhxgg1994@gmail.com) Thanks

Thanks. I have done.

**Comment by imneonizer** [comment]
can you send it to mneonizer@gmail.com please

**Comment by long123524** [comment]
> can you send it to [mneonizer@gmail.com](mailto:mneonizer@gmail.com) please

Thanks for your concern. I have sent it to your email.
