### ISSUE TITLE
作者您好，请问您最近有计算出或者找到ST-UNet的GFlops吗？

### ISSUE THREAD

**Issue by yuwxyun275** [long123524/BsiNet-torch#3]
我无法计算出ST-UNet对应文章的GFlops，碰巧看到你也遇到了同样的问题并且向作者发起了问题，由于最近急需比对所以想请问下你有找到吗？万分感谢您！

**Comment by long123524** [comment]
我也无法计算出ST-UNet对应文章的GFlops，如果您计算出来了，方便告知一下我吗？万分感谢您！
















在 2023-02-05 00:00:10，"yuwxyun275" ***@***.***> 写道：

我无法计算出ST-UNet对应文章的GFlops，碰巧看到你也遇到了同样的问题并且向作者发起了问题，由于最近急需比对所以想请问下你有找到吗？万分感谢您！
