### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by Wwwwzw1933** [long123524/BsiNet-torch#4]
你好，我想问下，您最后有预测出distance嘛？我看到test.py代码最后只是输出了一个？还将其作为为辅助任务，最后只是输出了mask?我在最后预测修改了代码，但是输出的距离预测图就是一直不太对。

**Comment by long123524** [comment]
outputs1，outputs2，outputs3分别是掩膜、边界和距离图，距离图你可以直接输出它，不需要进行二值化。

**Comment by long123524** [comment]
> 你好，我想问下，您最后有预测出distance嘛？我看到test.py代码最后只是输出了一个？还将其作为为辅助任务，最后只是输出了mask?我在最后预测修改了代码，但是输出的距离预测图就是一直不太对。

outputs1，outputs2，outputs3分别是掩膜、边界和距离图，距离图你可以直接输出它，不需要进行二值化。

**Comment by Wwwwzw1933** [comment]
代码中只有一个outputs1，所以我参照又写了输出的outputs2和outputs3，outputs2输出结果是边界图是正常的，但是outputs3的结果不太对，试了最大最小归一化等方法，输出的不是距离变化图。所以想问问您？谢谢！
![test](https://user-images.githubusercontent.com/104957902/236090946-b23de626-5e38-4cb9-9b0b-66cb6a11143a.png)

**Comment by long123524** [comment]
> 代码中只有一个outputs1，所以我参照又写了输出的outputs2和outputs3，outputs2输出结果是边界图是正常的，但是outputs3的结果不太对，试了最大最小归一化等方法，输出的不是距离变化图。所以想问问您？谢谢！ ![test](https://user-images.githubusercontent.com/104957902/236090946-b23de626-5e38-4cb9-9b0b-66cb6a11143a.png)
距离图outputs3你可以直接输出它，不需要进行二值化（距离大小不是非0即1，envi软件中可以查看它的直接输出的值（可能存在负数））；另外，你可以归一化它到0-1之间，再转成8位。值得注意的是，你应该查看距离任务的输出，看看是否存在问题，如果有，这可能是你标签导致的。

**Comment by Wwwwzw1933** [comment]
好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?

**Comment by long123524** [comment]
> 好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?

你大概是用错了，损失不可能这么大的，我训练时损失才0.多。建议你可视化距离图的标签看看，看看是否存在问题，对于0-255值大小的距离图应当在模型训练时归一化到0-1或-1到1后再进行网络训练。

**Comment by chl916185** [comment]
> > 好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?
> 
> 你大概是用错了，损失不可能这么大的，我训练时损失才0.多。建议你可视化距离图的标签看看，看看是否存在问题，对于0-255值大小的距离图应当在模型训练时归一化到0-1或-1到1后再进行网络训练。

标签制作的代码，可以分享一下嘛
@long123524

**Comment by long123524** [comment]
> > > 好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?
> > 
> > 
> > 你大概是用错了，损失不可能这么大的，我训练时损失才0.多。建议你可视化距离图的标签看看，看看是否存在问题，对于0-255值大小的距离图应当在模型训练时归一化到0-1或-1到1后再进行网络训练。
> 
> 标签制作的代码，可以分享一下嘛 @long123524

preprocess.py就是辅助标签生成的代码，mask可以用矢量化标注的方式得到

**Comment by chl916185** [comment]
> > > > 好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?
> > > 
> > > 
> > > 你大概是用错了，损失不可能这么大的，我训练时损失才0.多。建议你可视化距离图的标签看看，看看是否存在问题，对于0-255值大小的距离图应当在模型训练时归一化到0-1或-1到1后再进行网络训练。
> > 
> > 
> > 标签制作的代码，可以分享一下嘛 @long123524
> 
> preprocess.py就是辅助标签生成的代码，mask可以用矢量化标注的方式得到

请教一下，在制作边界、距离图标签时，是在切分后的子图上做的，还是原始大图上做的呢
@long123524

**Comment by long123524** [comment]
> > > > > 好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?
> > > > 
> > > > 
> > > > 你大概是用错了，损失不可能这么大的，我训练时损失才0.多。建议你可视化距离图的标签看看，看看是否存在问题，对于0-255值大小的距离图应当在模型训练时归一化到0-1或-1到1后再进行网络训练。
> > > 
> > > 
> > > 标签制作的代码，可以分享一下嘛 @long123524
> > 
> > 
> > preprocess.py就是辅助标签生成的代码，mask可以用矢量化标注的方式得到
> 
> 请教一下，在制作边界、距离图标签时，是在切分后的子图上做的，还是原始大图上做的呢 @long123524

我是在子图上做的。在大图上做标签，再切分子图也是可以的，这样可能更费时一些。

**Comment by chl916185** [comment]
> > > > > > 好的，我再试试，谢谢博主！之前有查看距离任务的输出值，可能我的标签存在一定的问题，我是用cv2.distanceTransform做的距离变化图，最后影像的格式均由浮点型转换为8位无符号整型，再转换为8位无符号整型做数据集进行训练，不知道这个过程成是否有问题，目前训练了不同的数据集得到的结果效果都还可以，但是不同数据集训练过程中，我发现Global Loss的值都非常大(都一百多)?
> > > > > 
> > > > > 
> > > > > 你大概是用错了，损失不可能这么大的，我训练时损失才0.多。建议你可视化距离图的标签看看，看看是否存在问题，对于0-255值大小的距离图应当在模型训练时归一化到0-1或-1到1后再进行网络训练。
> > > > 
> > > > 
> > > > 标签制作的代码，可以分享一下嘛 @long123524
> > > 
> > > 
> > > preprocess.py就是辅助标签生成的代码，mask可以用矢量化标注的方式得到
> > 
> > 
> > 请教一下，在制作边界、距离图标签时，是在切分后的子图上做的，还是原始大图上做的呢 @long123524
> 
> 我是在子图上做的。在大图上做标签，再切分子图也是可以的，这样可能更费时一些。

好的，谢谢啦
