### ISSUE TITLE
Conversion of the segmentation results (raster format) into field boundaries (vector format)

### ISSUE THREAD

**Issue by kcsumesh** [long123524/BsiNet-torch#5]
How were the segmentation results (raster format) converted into field boundaries (vector format)?

**Comment by long123524** [comment]
you can use the operation of raster (binary map) to vector, the gdal, arcpy and geopandas libriay can be used.

**Comment by long123524** [comment]
you can use the operation of raster (binary map) to vector, the gdal, arcpy and geopandas libriay can be used.

**Comment by long123524** [comment]
> How were the segmentation results (raster format) converted into field boundaries (vector format)?

you can use the operation of raster (binary map) to vector, the gdal, arcpy and geopandas libriay can be used.
