### ISSUE TITLE
请问有训练好的权重文件吗?

### ISSUE THREAD

**Issue by DoveEchoing** [long123524/BsiNet-torch#7]
请问有训练好的权重文件吗?最近复现您的模型,预测结果出现错误,想用您的权重文件试一下测试结果,看看是否与模型训练有关
如果您有训练好的权重文件,麻烦您发我邮箱297959382@qq.com,感谢!

**Comment by long123524** [comment]
Thank your concern. We have sent to your email.

**Comment by long123524** [comment]
> 请问有训练好的权重文件吗?最近复现您的模型,预测结果出现错误,想用您的权重文件试一下测试结果,看看是否与模型训练有关 如果您有训练好的权重文件,麻烦您发我邮箱[297959382@qq.com](mailto:297959382@qq.com),感谢!

Thank your concern. We have sent to your email.
