### ISSUE TITLE
About pretrained weights

### ISSUE THREAD

**Issue by xuliu-cyber** [long123524/BsiNet-torch#9]
I use the pretrained weight on a Xinjiang GF-2 image，but got the The following error：

Exception has occurred: RuntimeError
Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.down.0.l1.conv.bias", "module.down.0.l2.conv.bias", "module.down.1.l1.conv.bias", "module.down.1.l2.conv.bias", "module.down.2.l1.conv.bias", "module.down.2.l2.conv.bias", "module.down.3.l1.conv.bias", "module.down.3.l2.conv.bias", "module.down.4.l1.conv.bias", "module.down.4.l2.conv.bias", "module.up.0.l1.conv.bias", "module.up.0.l2.conv.bias", "module.up.1.l1.conv.bias", "module.up.1.l2.conv.bias", "module.up.2.l1.conv.bias", "module.up.2.l2.conv.bias", "module.up.3.l1.conv.bias", "module.up.3.l2.conv.bias".

**Comment by long123524** [comment]
> I use the pretrained weight on a Xinjiang GF-2 image，but got the The following error：
> 
> Exception has occurred: RuntimeError Error(s) in loading state_dict for DataParallel: Missing key(s) in state_dict: "module.down.0.l1.conv.bias", "module.down.0.l2.conv.bias", "module.down.1.l1.conv.bias", "module.down.1.l2.conv.bias", "module.down.2.l1.conv.bias", "module.down.2.l2.conv.bias", "module.down.3.l1.conv.bias", "module.down.3.l2.conv.bias", "module.down.4.l1.conv.bias", "module.down.4.l2.conv.bias", "module.up.0.l1.conv.bias", "module.up.0.l2.conv.bias", "module.up.1.l1.conv.bias", "module.up.1.l2.conv.bias", "module.up.2.l1.conv.bias", "module.up.2.l2.conv.bias", "module.up.3.l1.conv.bias", "module.up.3.l2.conv.bias".

This may be due to the different training environment. You can use "model.load_state_dict(torch.load(model_file),False)" to run it.
